language: php
php:
- '7.0'
services:
- mysql
- docker
env:
- NAME=learning VERSION=1.0.0
before_script:
- composer install --no-interaction
script:
- vendor/bin/phpunit
after_success:
- touch test_after_success.txt
- ll
- git add .
- git commit -am "Make source code standard and generate documentation"
- git push origin HEAD:$TRAVIS_BRANCH
notifications:
    slack: iofficez1:tnwGrbQkTr635Z5fsdjvYKe8