language: php
php:
- '7.0'
services:
- mysql
- docker
env:
- NAME=learning VERSION=1.0.0
before_script:
- composer install --no-interaction
script:
- vendor/bin/phpunit
after_success:
- misc/auto-deploy.sh
notifications:
    slack: iofficez1:tnwGrbQkTr635Z5fsdjvYKe8